import type { Metadata } from "next";
import {ReactNode} from "react";
import {Providers} from "@/app/providers";
import "../../public/styles/normalize.css";
import "@/styles/global.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
        <Providers>
            <body>
              {children}
            </body>
        </Providers>
    </html>
  );
}
